"""empty message

Revision ID: 55f40a164e8d
Revises: 
Create Date: 2018-02-08 14:27:29.867454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55f40a164e8d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cplc', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('capcfg',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cap_aid', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=2), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cap_aid')
    )
    op.create_table('capperso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cplc', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.Column('cap_aid', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cappkginfo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cap_name', sa.String(length=100), nullable=False),
    sa.Column('cap_version', sa.String(length=20), nullable=False),
    sa.Column('cap_perso', sa.String(length=1000), nullable=False),
    sa.Column('cap_aid', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('support_info',
    sa.Column('issue_no', sa.Integer(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('oem_vendor', sa.String(length=64), nullable=False),
    sa.Column('device_model', sa.String(length=64), nullable=True),
    sa.Column('sp_id', sa.String(length=16), nullable=False),
    sa.Column('environment', sa.String(length=64), nullable=False),
    sa.Column('issue_trace', sa.String(length=128), nullable=False),
    sa.Column('message', sa.String(length=1000), nullable=True),
    sa.Column('module_name', sa.String(length=128), nullable=True),
    sa.Column('handle_person', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('status', sa.String(length=3), nullable=True),
    sa.Column('reason', sa.String(length=1000), nullable=True),
    sa.Column('solution', sa.String(length=1000), nullable=True),
    sa.Column('advice', sa.String(length=1000), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('jira', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('issue_no')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('mobile', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('login_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('whitelist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('_cplc', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles_users',
    sa.Column('users', sa.Integer(), nullable=True),
    sa.Column('roles', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['roles'], ['role.id'], ),
    sa.ForeignKeyConstraint(['users'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles_users')
    op.drop_table('whitelist')
    op.drop_table('user')
    op.drop_table('support_info')
    op.drop_table('role')
    op.drop_table('cappkginfo')
    op.drop_table('capperso')
    op.drop_table('capcfg')
    op.drop_table('blacklist')
    # ### end Alembic commands ###
